/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ict.d_4;

import java.sql.Timestamp;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author pc
 */
public class frmRegister extends javax.swing.JFrame {
    
    // Logger: records errors and events to the console in a structured, professional way.
    // Unlike System.out.println, the Logger lets you mark severity levels (INFO, WARNING, SEVERE).
    // frmRegister.class.getName() sets the logger's name to "com.mycompany.ict.d_4.frmRegister".
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegister.class.getName());

    /**
     * Creates new form frmRegister
     */
    public frmRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtRFID = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtSection = new javax.swing.JTextField();
        txtParentEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setText("Register");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 194, 53));

        lblResult.setText("Result");
        getContentPane().add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));

        txtRFID.addActionListener(this::txtRFIDActionPerformed);
        getContentPane().add(txtRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 380, 30));

        txtfirstname.addActionListener(this::txtfirstnameActionPerformed);
        getContentPane().add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 360, 30));

        txtlastname.addActionListener(this::txtlastnameActionPerformed);
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 370, 30));

        txtSection.addActionListener(this::txtSectionActionPerformed);
        getContentPane().add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 370, 40));

        txtParentEmail.addActionListener(this::txtParentEmailActionPerformed);
        getContentPane().add(txtParentEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 370, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\Group 4 Figma\\student identification Jframe.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1020, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // STEP 1: Capture the current date and time for debugging purposes.
        // Timestamp wraps System.currentTimeMillis() (milliseconds since Jan 1, 1970) into a date-time object.
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());

        // Format the timestamp into a human-readable string: "yyyy-MM-dd HH:mm:ss"
        // e.g., "2026-04-18 08:30:00"
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formatted = timestamp.toLocalDateTime().format(formatter);

        // Print the formatted timestamp to the console (useful during testing/debugging)
        System.out.println(formatted);

        // STEP 2: Read the values typed into each text field on the registration form.
        // .getText() retrieves the current text content of a JTextField component.
        String rfid_number  = txtRFID.getText();        // The RFID card number scanned or typed
        String firstname    = txtfirstname.getText();   // Student's first name
        String lastname     = txtlastname.getText();    // Student's last name
        String section      = txtSection.getText();     // Student's class/section (e.g., "ICT-D4")
        String parent_email = txtParentEmail.getText(); // Parent's email for attendance notifications

        try {
            // STEP 3: Insert the new student record into the "students_information" table.
            // Uses ConnectXamppSQL's fluent builder: each .set() adds one column-value pair.
            // .execute() assembles the full SQL INSERT and runs it against the database.
            ConnectXamppSQL.Insert("students_information")
            .set("RFID_Number",  rfid_number)   // Save the RFID card number
            .set("Firstname",    firstname)      // Save the first name
            .set("Lastname",     lastname)       // Save the last name
            .set("Section",      section)        // Save the section
            .set("Parent_Email", parent_email)   // Save the parent's email address
            .execute(); // Run the SQL INSERT — this writes the record to MySQL
            
            // STEP 4: If the database INSERT succeeded, show a success popup.
            javax.swing.JOptionPane.showMessageDialog(null, "Successfully Registered!");
            // STEP 5: Open the Time-In window so the student can immediately scan in.
            new frmTimeIn().setVisible(true);
            // STEP 6: Close this registration window since we no longer need it.
            this.dispose();            
        } 
        
        catch (Exception e) {
            // If the INSERT fails (e.g., duplicate RFID, no database connection),
            // show an error message. Note: the message says "Unauthorized Student" but
            // this runs for ANY database exception, not just authorization failures.
            javax.swing.JOptionPane.showMessageDialog(null, "Unauthorized Student!");
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSectionActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFIDActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtParentEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParentEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParentEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtParentEmail;
    private javax.swing.JTextField txtRFID;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
