/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ict.d_4;

import java.sql.Timestamp;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author pc
 */
public class frmRegister extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegister.class.getName());

    /**
     * Creates new form frmRegister
     */
    public frmRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtRFID = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtSection = new javax.swing.JTextField();
        txtParentEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setText("Register");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 194, 53));

        lblResult.setText("Result");
        getContentPane().add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));

        txtRFID.addActionListener(this::txtRFIDActionPerformed);
        getContentPane().add(txtRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 380, 30));

        txtfirstname.addActionListener(this::txtfirstnameActionPerformed);
        getContentPane().add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 360, 30));

        txtlastname.addActionListener(this::txtlastnameActionPerformed);
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 370, 30));

        txtSection.addActionListener(this::txtSectionActionPerformed);
        getContentPane().add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 370, 40));

        txtParentEmail.addActionListener(this::txtParentEmailActionPerformed);
        getContentPane().add(txtParentEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 370, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\Group 4 Figma\\student identification Jframe.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1020, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
Timestamp timestamp = new Timestamp(System.currentTimeMillis());

DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
String formatted = timestamp.toLocalDateTime().format(formatter);

System.out.println(formatted);

        
        
        String rfid_number = txtRFID.getText();
        String firstname = txtfirstname.getText();
        String lastname = txtlastname.getText();
        String section = txtSection.getText();
        String parent_email = txtParentEmail.getText();

        try {
            ConnectXamppSQL.Insert("students_information")
            .set("RFID_Number", rfid_number)
            .set("Firstname", firstname)
            .set("Lastname", lastname)
            .set("Section", section)
            .set("Parent_Email", parent_email)
            .execute();
            
            javax.swing.JOptionPane.showMessageDialog(null, "Successfully Registered!");         
              new frmTimeIn().setVisible(true);
            this.dispose();            
                  } 
        
        
            catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog(null, "Unauthorized Student!");
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSectionActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFIDActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtParentEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParentEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParentEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtParentEmail;
    private javax.swing.JTextField txtRFID;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
