/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ict.d_4;

import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author pc
 */
public class frmTimeOut extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmTimeOut.class.getName());

    /**
     * Creates new form frmTimeOut
     */
    public frmTimeOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRFID_A = new javax.swing.JTextField();
        txtPM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRFID_A.addActionListener(this::txtRFID_AActionPerformed);
        txtRFID_A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRFID_AKeyPressed(evt);
            }
        });
        getContentPane().add(txtRFID_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 270, 40));

        txtPM.addActionListener(this::txtPMActionPerformed);
        txtPM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPMKeyPressed(evt);
            }
        });
        getContentPane().add(txtPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\Group 4 Figma\\TimeOut.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRFID_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFID_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFID_AActionPerformed

    private void txtRFID_AKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFID_AKeyPressed
        DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("hh:mm a"); 
        
        LocalDateTime now = LocalDateTime.now();
            String time = now.format(TIME_FORMAT);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String capturedValue = txtRFID_A.getText().trim();
            if (!capturedValue.isEmpty()) {                
                AttendanceService.processAttendance(capturedValue, "OUT", this);
                    
            }
            txtRFID_A.setText(""); // Clear the input field after processing
             txtPM.setText(time);
        }
        
    }//GEN-LAST:event_txtRFID_AKeyPressed

    private void txtPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMActionPerformed

    private void txtPMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPMKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmTimeOut().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPM;
    private javax.swing.JTextField txtRFID_A;
    // End of variables declaration//GEN-END:variables
}
