/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ict.d_4;

import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author pc
 */
public class frmTimeIn extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmTimeIn.class.getName());

    // TODO: Replace these with external config or secure storage before production
    private static final String EMAIL_FROM = "devtrish129@gmail.com";
    private static final String EMAIL_PASSWORD = "opna mwyy novk xaan"; // App password required if 2FA enabled
    private static final String SCHOOL_NAME = "Your School Name";
    private static final String SCHOOL_PHONE = "+63-912-345-6789";

    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("hh:mm a");
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    /**
     * Creates new form frmTimeIn
     */
    public frmTimeIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAM = new javax.swing.JTextField();
        txtRFID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAM.addActionListener(this::txtAMActionPerformed);
        txtAM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAMKeyPressed(evt);
            }
        });
        getContentPane().add(txtAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 270, 50));

        txtRFID.addActionListener(this::txtRFIDActionPerformed);
        txtRFID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRFIDKeyPressed(evt);
            }
        });
        getContentPane().add(txtRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\Group 4 Figma\\TimeIn.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAMActionPerformed
        
    }//GEN-LAST:event_txtAMActionPerformed

    private void txtAMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMKeyPressed
        //TODO add your handling code here:
    }//GEN-LAST:event_txtAMKeyPressed

    private void txtRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFIDActionPerformed

    private void txtRFIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFIDKeyPressed
       DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("hh:mm a"); 
        
        LocalDateTime now = LocalDateTime.now();
            String time = now.format(TIME_FORMAT);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String capturedValue = txtRFID.getText().trim();
            if (!capturedValue.isEmpty()) {                
                AttendanceService.processAttendance(capturedValue, "IN", this);
                    
            }
            txtRFID.setText(""); // Clear the input field after processing
             txtAM.setText(time);
        }
        
    }//GEN-LAST:event_txtRFIDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmTimeIn().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtRFID;
    // End of variables declaration//GEN-END:variables
}
