/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ict.d_4;

import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author pc
 */
public class frmTimeIn extends javax.swing.JFrame {
    
    // Logger: used to record serious errors to the console with proper severity levels.
    // Better than System.out.println because you can filter by INFO / WARNING / SEVERE.
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmTimeIn.class.getName());

    // TODO: Replace these with external config or secure storage before production
    // These credentials are used by AttendanceService to send email notifications.
    // They are declared here as constants but the actual sending happens in AttendanceService.
    private static final String EMAIL_FROM     = "devtrish129@gmail.com";
    private static final String EMAIL_PASSWORD = "opna mwyy novk xaan"; // App password required if 2FA enabled
    private static final String SCHOOL_NAME    = "Your School Name";
    private static final String SCHOOL_PHONE   = "+63-912-345-6789";

    // DATE/TIME FORMATTERS ───────────────────────────────────────────────────
    // These formatters define how the current time is displayed in the txtAM field.
    // TIME_FORMAT → 12-hour clock with AM/PM, e.g., "08:30 AM"
    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("hh:mm a");
    // DATE_FORMAT → ISO date string, e.g., "2026-04-18"
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    /**
     * Creates new form frmTimeIn
     */
    public frmTimeIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAM = new javax.swing.JTextField();
        txtRFID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAM.addActionListener(this::txtAMActionPerformed);
        txtAM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAMKeyPressed(evt);
            }
        });
        getContentPane().add(txtAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 270, 50));

        txtRFID.addActionListener(this::txtRFIDActionPerformed);
        txtRFID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRFIDKeyPressed(evt);
            }
        });
        getContentPane().add(txtRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\Group 4 Figma\\TimeIn.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAMActionPerformed
        
    }//GEN-LAST:event_txtAMActionPerformed

    private void txtAMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMKeyPressed
        //TODO add your handling code here:
    }//GEN-LAST:event_txtAMKeyPressed

    private void txtRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFIDActionPerformed

    private void txtRFIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFIDKeyPressed
        // Create a formatter for displaying the time in the txtAM field.
        // This is a local copy — the class-level TIME_FORMAT constant could also be used.
        DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("hh:mm a"); 
        
        // Capture the current date and time at the moment the key was pressed.
        LocalDateTime now = LocalDateTime.now();
        // Format just the time portion: e.g., "08:30 AM"
        String time = now.format(TIME_FORMAT);

        // Only process the RFID when the ENTER key is pressed.
        // The RFID scanner simulates keyboard input and ends with an ENTER key press.
        // VK_ENTER is the virtual key code constant for the Enter key.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Read whatever text is currently in the RFID input field.
            // .trim() removes any accidental leading/trailing spaces from the scanner.
            String capturedValue = txtRFID.getText().trim();

            // Only process if the field is not empty (a valid RFID was scanned).
            if (!capturedValue.isEmpty()) {
                // Delegate to AttendanceService to handle the full attendance workflow:
                // database insert + duplicate check + email notification + success popup.
                // "IN" tells the service that this is a Time-In scan.
                AttendanceService.processAttendance(capturedValue, "IN", this);
            }

            txtRFID.setText(""); // Clear the RFID input field so it's ready for the next scan
            txtAM.setText(time); // Display the formatted time in the Time-In display field
        }
        
    }//GEN-LAST:event_txtRFIDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmTimeIn().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtRFID;
    // End of variables declaration//GEN-END:variables
}
